<?php

namespace common\models;

use common\components\BaseConfig;
use common\components\BaseController;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * This is the model class for table "{{%mall_spec_param}}".
 *
 * @property integer $id
 * @property integer $cid
 * @property integer $group_id
 * @property string $name
 * @property integer $data_type
 * @property string $unit
 * @property integer $generic
 * @property integer $searching
 * @property string $segments
 */
class MallSpecParam extends \common\components\BaseModel
{

    const  GENERIC_TYPE = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%mall_spec_param}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cid', 'group_id', 'data_type', 'generic', 'searching'], 'integer'],
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['unit', 'display_type'], 'string', 'max' => 16],
            [['segments'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'cid' => Yii::t('mall', 'Category'),
            'group_id' => Yii::t('mall', 'Mall Spec Group'),
            'name' => Yii::t('mall', 'Params Name'),
            'data_type' => Yii::t('mall', 'Data Type'),
            'unit' => Yii::t('mall', 'Unit'),
            'generic' => Yii::t('mall', 'Generic'),
            'searching' => Yii::t('mall', 'Searching'),
            'segments' => Yii::t('mall', 'Segments'),
            'display_type' => Yii::t('app', 'Type'),
        ]);
    }

    public function submitData($params, $fromName = null)
    {
        $fromName === null && $fromName = $this->formName();
        $segmentsSortName = $segmentsSort = [];
        if (isset($params[$fromName]['items'])) {
            isset($params[$fromName]['items']['sort']) && $segmentsSort = $params[$fromName]['items']['sort'];
            isset($params[$fromName]['items']['name']) && $segmentsSortName = $params[$fromName]['items']['name'];
            foreach ($segmentsSortName as $key => $item) {
                $arr = [
                    'index' => $key,
                    'sort' => $segmentsSort[$key],
                    'name' => $item,
                ];
                $segments[] = $arr;
            }
        }
//        $segments = array_combine($segmentsSortName, $segmentsSort);
        if (!empty($segments)) $params[$fromName]['segments'] = Json::encode($segments);

        return $this->load($params) && $this->save();
    }

    public function getIsSelectDis()
    {
        return $this->display_type === BaseConfig::FORM_SELECT;
    }

    public function getDataTypeFormat()
    {
        return BaseConfig::getDataTypes($this->data_type);
    }

    public function getGenericFormat()
    {
        return BaseConfig::getYesNoItems($this->generic);
    }

    public function getSearchingFormat()
    {
        return BaseConfig::getYesNoItems($this->searching);
    }

    public function getGroup()
    {
        return $this->hasOne(MallSpecGroup::class, ['id' => 'group_id']);
    }

    public function getCategory()
    {
        return $this->hasOne(MallCategory::class, ['id' => 'cid']);
    }

    public function beforeSave($insert)
    {
        if ($this->group) $this->cid = $this->group->cid;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
