<?php
declare(strict_types=1);
/**
 * Created by PhpStorm
 * User: Administrator
 * Author: JieChengYang
 * Date: 2020/3/15
 * Time: 19:52
 */

namespace common\models;


use common\components\BaseConfig;
use yii\helpers\ArrayHelper;

class MallCategory extends Category
{

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->type = BaseConfig::PRODUCT_CATALOG_ID;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function loadData($level = null)
    {
        $query = self::find()->product()->orderBy(['sort' => SORT_ASC]);
        if ($level === 1) {
            return $query->where(['parent_id' => 0])->asArray()->all();
        }

        return $query->asArray()->all();
    }

    public static function getCatalogList($pid = 0)
    {
        $rows = self::find()->product()
            ->select(['id', 'parent_id', 'name', 'path'])
            ->andWhere(['parent_id' => $pid])
            ->orderBy(['sort' => SORT_ASC])
            ->asArray()
            ->all();
        $data = [];
        foreach ($rows as $row) {
            $count = count(explode(',', $row['path']));
            $row['level'] = $count ? $count - 1 : $count;
            unset($row['parent_id']);
            $data[] = $row;
        }

        return $data;
    }
}