<?php
declare(strict_types=1);
/**
 * Created by PhpStorm
 * User: Administrator
 * Author: JieChengYang
 * Date: 2020/3/15
 * Time: 19:52
 */

namespace common\models;


use common\components\BaseConfig;

class MallCategory extends  Category
{

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->type = BaseConfig::PRODUCT_CATALOG_ID;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function loadData()
    {
        return self::find()->product()->asArray()->all();
    }
}